apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    app.kubernetes.io/app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/app: mysql   