apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: app
  labels:
    app.kubernetes.io/app: employees
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: employees
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: employees
    spec:
      containers:
      - name: application
        image: 203171546861.dkr.ecr.us-east-1.amazonaws.com/clo835-jcaranay-assignment1-app-repo:v1.0
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SESSION_TOKEN
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DBPWD
        - name: DBHOST
          value: mysql-0.mysql-headless.db.svc.cluster.local
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBPORT
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: BG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BG
        ports:
        - containerPort: 81
      imagePullSecrets:
      - name: ecr-secret