apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: final
  labels:
    app.kubernetes.io/app: employees
spec:
  type: LoadBalancer
  ports:
  - port: 80    
    targetPort: 81
  selector:
    app.kubernetes.io/app: employees