apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: db
spec:
  clusterIP: None  # Makes it a headless service
  selector:
    app.kubernetes.io/app: mysql
  ports:
  - port: 3306
    targetPort: 3306