apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplication
  labels:
    app.kubernetes.io/app: employees
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/app: employees
    spec:
      containers:
      - name: aplication
        image: 203171546861.dkr.ecr.us-east-1.amazonaws.com/clo835-jcaranay-assignment1-app-repo:latest
        env:
        - name: DBHOST
          value: mysql.db.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db
              key: USER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db
              key: PASSWORD
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret
