apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
  - name: application
    image: 203171546861.dkr.ecr.us-east-1.amazonaws.com/clo835-jcaranay-assignment1-app-repo:latest
    env:
    - name: DBHOST
      value: mysql.db.svc.cluster.local
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: db
          key: USER
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: db
          key: PASSWORD
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: ecr-secret