apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
    app.kubernetes.io/app: employees
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app.kubernetes.io/app: employees   