apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: database
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: mysql
        image: 203171546861.dkr.ecr.us-east-1.amazonaws.com/clo835-jcaranay-assignment1-db-repo:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: PASSWORD
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: ecr-secret