apiVersion: v1
kind: Pod
metadata:
  name: db-con
  labels:
    app: db-con
spec:
  containers:
  - name: db-container
    image: 203171546861.dkr.ecr.us-east-1.amazonaws.com/clo835-jcaranay-assignment1-db-repo:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db
          key: PASSWORD
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: ecr-secret
